name: Build Pull Request

on:
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        run: mvn -ntp -B package